apiVersion: apps/v1
kind: Deployment
metadata:
  name: swapispringboot-deployment
  namespace: apiexemplo
spec:
  selector:
    matchLabels:
      app: swapispringboot
  template: 
    metadata:
        name: swapispringboot
        labels:
          app: swapispringboot
    spec:
        containers:
          - name: swapispringboot-container
            image: $dck-accountid/$dck-repository:swapispringboot-$githash
            env:
              - name: SPRING_PROFILES_ACTIVE
                value: "dev"
            ports:
              - containerPort: 5000
              - containerPort: 9091
            livenessProbe:
              httpGet:
                path: /actuator/health
                port: 9091
              initialDelaySeconds: 120
              periodSeconds: 60
              timeoutSeconds: 10
              successThreshold: 1
              failureThreshold: 2
            readinessProbe:
              httpGet:
                path: /actuator/health
                port: 9091
              initialDelaySeconds: 120
              periodSeconds: 10
              timeoutSeconds: 10
