apiVersion: v1
kind: Service
metadata: 
  name: svc-swapispringboot
  namespace: apiexemplo
spec:
  type: ClusterIP
  selector:
      app: swapispringboot
  ports:
    - port: 5000
      name: http-5000
      protocol: TCP
      targetPort: 5000
    - port: 9091
      name: http-prometheus
      protocol: TCP
      targetPort: 9091